[package]
name = "rust-git"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
sha1 = "0.10"

[dev-dependencies]

[[bin]]
name = "rust-git"
path = "src/main.rs"
